//------------------------------------------------------------------------
// Copyright(c) 2023 JKU.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"mmsSynth.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"mmsSynth VST3 (64Bit)"
#else
#define stringFileDescription	"mmsSynth VST3"
#endif
#define stringCompanyName		"JKU\0"
#define stringLegalCopyright	"Copyright(c) 2023 JKU."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
